spring:
  application:
    name: spring-ai-workshop
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

#api:
#  ai:
#    openai:
#      api-key: ${OPENAI_API_KEY}
#      chat:
#        options:
#          model: gpt-4o
